from typing import List, Dict, Any

COMPANY_SOURCES: List[Dict[str, Any]] = [
    {"company_name": "Google", "careers_url": "https://careers.google.com", "provider_name": "google", "parser_function": "parse_google"},
    {"company_name": "Microsoft", "careers_url": "https://careers.microsoft.com", "provider_name": "microsoft", "parser_function": "parse_microsoft"},
    {"company_name": "Amazon", "careers_url": "https://aws.amazon.com/careers", "provider_name": "amazon", "parser_function": "parse_amazon"},
    {"company_name": "Adobe", "careers_url": "https://adobe.com/careers", "provider_name": "adobe", "parser_function": "parse_adobe"},
    {"company_name": "NVIDIA", "careers_url": "https://nvidia.com/careers", "provider_name": "nvidia", "parser_function": "parse_nvidia"},
    {"company_name": "Intel", "careers_url": "https://intel.com/jobs", "provider_name": "intel", "parser_function": "parse_intel"},
    {"company_name": "Oracle", "careers_url": "https://careers.oracle.com", "provider_name": "oracle", "parser_function": "parse_oracle"},
    {"company_name": "Cisco", "careers_url": "https://jobs.cisco.com", "provider_name": "cisco", "parser_function": "parse_cisco"},
    {"company_name": "IBM", "careers_url": "https://ibm.com/careers", "provider_name": "ibm", "parser_function": "parse_ibm"},
    {"company_name": "SAP", "careers_url": "https://jobs.sap.com", "provider_name": "sap", "parser_function": "parse_sap"},
    {"company_name": "Salesforce", "careers_url": "https://salesforce.com/company/careers", "provider_name": "salesforce", "parser_function": "parse_salesforce"},
    {"company_name": "ServiceNow", "careers_url": "https://jobs.servicenow.com", "provider_name": "servicenow", "parser_function": "parse_servicenow"},
    {"company_name": "Atlassian", "careers_url": "https://atlassian.com/company/careers", "provider_name": "atlassian", "parser_function": "parse_atlassian"},
    {"company_name": "Zoho", "careers_url": "https://zoho.com/careers", "provider_name": "zoho", "parser_function": "parse_zoho"},
    {"company_name": "Freshworks", "careers_url": "https://freshworks.com/careers", "provider_name": "freshworks", "parser_function": "parse_freshworks"},
    {"company_name": "Qualcomm", "careers_url": "https://qualcomm.com/careers", "provider_name": "qualcomm", "parser_function": "parse_qualcomm"},
    {"company_name": "AMD", "careers_url": "https://amd.com/en/careers", "provider_name": "amd", "parser_function": "parse_amd"},
    {"company_name": "Accenture", "careers_url": "https://accenture.com/careers", "provider_name": "accenture", "parser_function": "parse_accenture"},
    {"company_name": "Capgemini", "careers_url": "https://capgemini.com/careers", "provider_name": "capgemini", "parser_function": "parse_capgemini"},
    {"company_name": "Deloitte", "careers_url": "https://deloitte.com/careers", "provider_name": "deloitte", "parser_function": "parse_deloitte"},
    {"company_name": "EY", "careers_url": "https://ey.com/careers", "provider_name": "ey", "parser_function": "parse_ey"},
    {"company_name": "PwC", "careers_url": "https://pwc.com/careers", "provider_name": "pwc", "parser_function": "parse_pwc"},
    {"company_name": "TCS", "careers_url": "https://tcs.com/careers", "provider_name": "tcs", "parser_function": "parse_tcs"},
    {"company_name": "Infosys", "careers_url": "https://infosys.com/careers", "provider_name": "infosys", "parser_function": "parse_infosys"},
    {"company_name": "Wipro", "careers_url": "https://wipro.com/careers", "provider_name": "wipro", "parser_function": "parse_wipro"},
    {"company_name": "HCL", "careers_url": "https://hcl.com/careers", "provider_name": "hcl", "parser_function": "parse_hcl"},
    {"company_name": "Tech Mahindra", "careers_url": "https://techmahindra.com/careers", "provider_name": "tech_mahindra", "parser_function": "parse_tech_mahindra"},
    {"company_name": "Cognizant", "careers_url": "https://cognizant.com/careers", "provider_name": "cognizant", "parser_function": "parse_cognizant"},
    {"company_name": "LTIMindtree", "careers_url": "https://ltimes.com/careers", "provider_name": "ltimes", "parser_function": "parse_ltimes"},
    {"company_name": "JPMorgan Chase", "careers_url": "https://jpmorganchase.com/careers", "provider_name": "jpmorgan", "parser_function": "parse_jpmorgan"},
    {"company_name": "Goldman Sachs", "careers_url": "https://goldmansachs.com/careers", "provider_name": "goldman", "parser_function": "parse_goldman"},
    {"company_name": "Morgan Stanley", "careers_url": "https://morganstanley.com/careers", "provider_name": "morgan_stanley", "parser_function": "parse_morgan_stanley"},
    {"company_name": "PhonePe", "careers_url": "https://phonepe.com/careers", "provider_name": "phonepe", "parser_function": "parse_phonepe"},
    {"company_name": "Razorpay", "careers_url": "https://razorpay.com/careers", "provider_name": "razorpay", "parser_function": "parse_razorpay"},
    {"company_name": "Flipkart", "careers_url": "https://flipkart.com/careers", "provider_name": "flipkart", "parser_function": "parse_flipkart"},
    {"company_name": "Swiggy", "careers_url": "https://swiggy.com/careers", "provider_name": "swiggy", "parser_function": "parse_swiggy"},
    {"company_name": "Meesho", "careers_url": "https://meesho.com/careers", "provider_name": "meesho", "parser_function": "parse_meesho"},
    {"company_name": "Paytm", "careers_url": "https://paytm.com/careers", "provider_name": "paytm", "parser_function": "parse_paytm"},
    {"company_name": "Nutanix", "careers_url": "https://nutanix.com/careers", "provider_name": "nutanix", "parser_function": "parse_nutanix"},
    {"company_name": "Cloudflare", "careers_url": "https://cloudflare.com/careers", "provider_name": "cloudflare", "parser_function": "parse_cloudflare"},
    {"company_name": "Snowflake", "careers_url": "https://snowflake.com/careers", "provider_name": "snowflake", "parser_function": "parse_snowflake"},
    {"company_name": "OpenAI", "careers_url": "https://openai.com/careers", "provider_name": "openai", "parser_function": "parse_openai"},
    {"company_name": "Anthropic", "careers_url": "https://anthropic.com/careers", "provider_name": "anthropic", "parser_function": "parse_anthropic"},
    {"company_name": "Stripe", "careers_url": "https://stripe.com/careers", "provider_name": "stripe", "parser_function": "parse_stripe"},
    {"company_name": "Datadog", "careers_url": "https://datadoghq.com/careers", "provider_name": "datadog", "parser_function": "parse_datadog"},
    {"company_name": "GitHub", "careers_url": "https://github.com/about/careers", "provider_name": "github", "parser_function": "parse_github"},
    {"company_name": "Netflix", "careers_url": "https://netflix.com/jobs", "provider_name": "netflix", "parser_function": "parse_netflix"},
    {"company_name": "Booking.com", "careers_url": "https://booking.com/careers", "provider_name": "booking", "parser_function": "parse_booking"},
    {"company_name": "Uber", "careers_url": "https://uber.com/us/en/careers", "provider_name": "uber", "parser_function": "parse_uber"},
    {"company_name": "Airbnb", "careers_url": "https://airbnb.com/careers", "provider_name": "airbnb", "parser_function": "parse_airbnb"},
]