from typing import List, Dict, Any

COMPANY_SOURCES: List[Dict[str, Any]] = [
    {"company_name": "Google", "careers_url": "https://careers.google.com", "provider_name": "google", "parser_function": "parse_google"},
    {"company_name": "Microsoft", "careers_url": "https://careers.microsoft.com", "provider_name": "microsoft", "parser_function": "parse_microsoft"},
    {"company_name": "Amazon", "careers_url": "https://aws.amazon.com/careers", "provider_name": "amazon", "parser_function": "parse_amazon"},
    {"company_name": "Adobe", "careers_url": "https://adobe.com/careers", "provider_name": "adobe", "parser_function": "parse_adobe"},
    {"company_name": "Oracle", "careers_url": "https://careers.oracle.com", "provider_name": "oracle", "parser_function": "parse_oracle"},
    {"company_name": "IBM", "careers_url": "https://ibm.com/careers", "provider_name": "ibm", "parser_function": "parse_ibm"},
    {"company_name": "Intel", "careers_url": "https://intel.com/jobs", "provider_name": "intel", "parser_function": "parse_intel"},
    {"company_name": "Cisco", "careers_url": "https://jobs.cisco.com", "provider_name": "cisco", "parser_function": "parse_cisco"},
    {"company_name": "Salesforce", "careers_url": "https://salesforce.com/company/careers", "provider_name": "salesforce", "parser_function": "parse_salesforce"},
    {"company_name": "NVIDIA", "careers_url": "https://nvidia.com/careers", "provider_name": "nvidia", "parser_function": "parse_nvidia"},
    {"company_name": "Qualcomm", "careers_url": "https://qualcomm.com/careers", "provider_name": "qualcomm", "parser_function": "parse_qualcomm"},
    {"company_name": "SAP", "careers_url": "https://jobs.sap.com", "provider_name": "sap", "parser_function": "parse_sap"},
    {"company_name": "Zoho", "careers_url": "https://zoho.com/careers", "provider_name": "zoho", "parser_function": "parse_zoho"},
    {"company_name": "Freshworks", "careers_url": "https://freshworks.com/careers", "provider_name": "freshworks", "parser_function": "parse_freshworks"},
    {"company_name": "Razorpay", "careers_url": "https://razorpay.com/careers", "provider_name": "razorpay", "parser_function": "parse_razorpay"},
    {"company_name": "PhonePe", "careers_url": "https://phonepe.com/careers", "provider_name": "phonepe", "parser_function": "parse_phonepe"},
    {"company_name": "Groww", "careers_url": "https://groww.com/careers", "provider_name": "groww", "parser_function": "parse_groww"},
    {"company_name": "BrowserStack", "careers_url": "https://browserstack.com/careers", "provider_name": "browserstack", "parser_function": "parse_browserstack"},
    {"company_name": "Postman", "careers_url": "https://postman.com/careers", "provider_name": "postman", "parser_function": "parse_postman"},
    {"company_name": "Flipkart", "careers_url": "https://flipkart.com/careers", "provider_name": "flipkart", "parser_function": "parse_flipkart"},
    {"company_name": "Meesho", "careers_url": "https://meesho.com/careers", "provider_name": "meesho", "parser_function": "parse_meesho"},
    {"company_name": "Swiggy", "careers_url": "https://swiggy.com/careers", "provider_name": "swiggy", "parser_function": "parse_swiggy"},
    {"company_name": "CRED", "careers_url": "https://cred.club/careers", "provider_name": "cred", "parser_function": "parse_cred"},
]