name: Daily Job Alert

on:
  schedule:
    # 7:00 PM IST = 1:30 PM UTC
    - cron: "30 13 * * *"

  workflow_dispatch:

jobs:
  send-job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger job collection
        run: |
          curl -X POST ${{ secrets.RENDER_URL }}/jobs/refresh

      - name: Wait for scraping
        run: sleep 30

      - name: Send today's email
        run: |
          curl -X POST ${{ secrets.RENDER_URL }}/email/send-today
